language: python
python:
  - "3.7"
branches:
  only:
    - master
install:
  - pip install -r requirements.txt
deploy:
  provider: firebase
script:
  - echo "deploying"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN